### ISSUE TITLE
Track Response Time

### ISSUE THREAD

**Issue by ericrange** [mscdex/cap#22]
hey is it possible to get the time when a "connection" is answered? as i see in your samples its just possible to get the time when a packet arrives... but can i also get the time or event when an connection is answered? is this possible somehow? so for example... i want the time between the request of a browser and the reponse from the server.

**Comment by mscdex** [comment]
That's a little more involved because you would most likely have to parse the packets. It's certainly doable though and you could use the built-in node HTTP parser as a starting point, that will require some digging into node core to see how the internal http module uses the parser binding. That way you could get the time at the end of the request and then get the time again when the first bytes of the response is sent (or maybe after the whole response is sent or when you see a TCP FIN flag).
