### ISSUE TITLE
Question: Installing on Windows

### ISSUE THREAD

**Issue by alexandrubau** [mscdex/cap#34]
Hi,

I'm not able to install `cap` on Windows. I receive the following error:
  
![one](https://cloud.githubusercontent.com/assets/1225661/10618073/91f8c33c-7776-11e5-9f96-f97b7c52fbec.png)
![two](https://cloud.githubusercontent.com/assets/1225661/10618074/922a041a-7776-11e5-94b9-49d7774806af.png)
![three](https://cloud.githubusercontent.com/assets/1225661/10618075/92350e14-7776-11e5-9e4e-0a85e4e24eea.png)

I have installed:
- Winpcap
- NodeJS ( with npm )
- Python 2.7
- VisualStudio Community ( I received a previous warning saying that I need to install VisualStudio in order to install `cap` )

To install `cap` I used `npm install cap --save`

I installed without any problems `cap` on my OS X machine. Is there a problem if I copy it from my OS X machine into my Windows machine ? Or do I need to run `npm install cap` on my Windows machine ?

What am I doing wrong ?

Thanks

**Comment by mscdex** [comment]
Yes, you have to install it separately on Windows because it's a compiled thing.

Secondly, are you sure you selected Visual C++ when you installed Visual Studio? It's possible you installed other components instead (e.g. C#). If you did install Visual C++, then you might try installing from one of the special Visual Studio command prompts that explicitly sets up the environment for you.

If you're still having problems after that, your issue is better placed at the [`node-gyp` issue tracker](https://github.com/nodejs/node-gyp) as this is not a problem with `cap` itself.

**Comment by alexandrubau** [comment]
I think it's related to https://github.com/nodejs/node-gyp/issues/694 . I'll try there.
Maybe I'll make some time to modify the readme to help others and I'll hit you with a pull request.

Thanks very much for your help.

**Comment by alexandrubau** [comment]
But the `cap` module requires Python in order to run on Windows ?

**Comment by mscdex** [comment]
All node addons require Python and a compiler, that means VS on Windows or clang/gcc on *nix.

**Comment by alexandrubau** [comment]
What I wanted to ask was that Python is required *only* to compile the module ?
Will it be required further if I say, move the module to another Windows machine ?

**Comment by mscdex** [comment]
If you move your `node_modules` to another machine of the same platform and architecture (and provided the appropriate C/C++ libraries are installed), then you don't need to recompile again.
